version: '3.8'

services:
  backend:
    image: ayushkrjaiswal/course-backend
    container_name: course-backend
    networks:
      - course-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: qwerty
      DB_URL: jdbc:mysql://mysqldb:3306/courseDb
    ports:
      - "8080:8080"

  frontend:
    image: ayushkrjaiswal/course-frontend
    container_name: course-frontend
    networks:
      - course-network
    environment:
      NUXT_PUBLIC_BACKEND_URL: http://localhost:8080/api
    ports:
      - "3000:3000"


  database:
    image: mysql
    container_name: mysqldb
    networks:
      - course-network
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: courseDb
    ports:
      - "3310:3306"

networks:
  course-network:
    driver: bridge