spring:
  application:
    name: course-backend

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    dev.archimedes.coursebackend: debug